name: package

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron: 0 8 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: javasetup
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Installs
        run: |
          pip install --pre hamlet-cli
          pip install awscli

          sudo apt-get update
          sudo apt-get install -y jq dos2unix

      - name: Run Tests
        env:
          TEST_OUTPUT_DIR: ${{ github.workspace }}/hamlet_tests
        run: |
          ./test.sh

      - name: Shared Plugin Results
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'hamlet_tests/shared/junit.xml'
          fail_on_failure: true
          require_tests: true
          check_name: Shared Plugin Results

      - name: AWS Plugin Results
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'hamlet_tests/aws/junit.xml'
          fail_on_failure: true
          require_tests: true
          check_name: AWS Plugin Results

      - name: Azure Plugin Results
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'hamlet_tests/azure/junit.xml'
          fail_on_failure: true
          require_tests: true
          check_name: Azure Plugin Results

      - id: get_tag_name
        name: image tag prefix
        run: |
          if [[ "${{ github.event_name}}" == "schedule" ]]; then
            echo ::set-output name=TAG_NAME::nightly
            echo ::set-output name=PUSH_IMAGE::true
            exit 0
          fi

          if [[ "${{ github.event_name}}" == "workflow_dispatch" ]]; then
            echo ::set-output name=TAG_NAME::latest
            echo ::set-output name=PUSH_IMAGE::true
            exit 0
          fi

          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo ::set-output name=TAG_NAME::latest
            echo ::set-output name=PUSH_IMAGE::true
            exit 0
          fi

          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}
            echo ::set-output name=PUSH_IMAGE::true
            exit 0
          fi

          echo ::set-output name=TAG_NAME::test
          echo ::set-output name=PUSH_IMAGE::false

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Release
        uses: docker/build-push-action@v2
        with:
          push: ${{ startsWith(steps.get_tag_name.outputs.PUSH_IMAGE, 'true') }}
          tags: "ghcr.io/${{github.repository}}:${{ steps.get_tag_name.outputs.TAG_NAME }}"
          target: base_package
