name: package

on:
  push:
  schedule:
    - cron: 0 8 * * *

jobs:
  build:
    env:
      ENGINE: 'unicycle'

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: javasetup
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Installs
        run: |
          pip install --pre hamlet-cli
          pip install awscli

          sudo apt-get update
          sudo apt-get install -y jq dos2unix

      - name: Run Tests
        env:
          TEST_OUTPUT_DIR: ${{ github.workspace }}/hamlet_tests
        run: |
          ./test.sh "${ENGINE}"

      - name: setup github
        run: |
         git config --global user.name "Github"
         git config --global user.email "noreply@github.com"

      - name: add build data
        working-directory: state
        run: |
          hamlet engine describe-engine -n "${ENGINE}" > engine.json
          git add ./
          git commit -m 'chore: add latest build details'

      - name: bump rc version
        if: github.ref == 'refs/heads/main'
        run: |
          pip install -r requirements.txt
          bump2version build

      - name: Shared Plugin Results
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'hamlet_tests/shared/junit.xml'
          fail_on_failure: true
          require_tests: true
          check_name: Shared Plugin Results

      - name: AWS Plugin Results
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'hamlet_tests/aws/junit.xml'
          fail_on_failure: true
          require_tests: true
          check_name: AWS Plugin Results

      - name: Azure Plugin Results
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'hamlet_tests/azure/junit.xml'
          fail_on_failure: true
          require_tests: true
          check_name: Azure Plugin Results

      - name: docker meta details
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{github.repository}}
          flavor: |
            latest=auto
          tags: |
            type=semver,pattern={{version}}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Release
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'scheduled' || startsWith(github.ref, 'refs/tags/*') || github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: base_package

      - name: Bump to next dev release
        if: startsWith(github.ref, 'refs/tags/' )
        working-directory: ./hamlet-cli
        run: |
          bump2version minor

      - name: Push Tags
        run: |
          git push --tags

      - name: Create Pull Request
        id: release_pr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore: version bump"
          delete-branch: true
          title: 'chore: update release details'
          body: 'latest build of the tram completed. Merge this PR to acknowledge release'
          labels: 'chore'
          base: 'main'
          branch: create-pull-request/release_bump
